#INSTRUCTION!!!
#Everything is already automated, but only in some cases you will have to run the command from the prepare.sh file.


#MAIN VARIABLE
#MODE=prod
#DJANGO_SETTINGS_MODULE=config.settings.${MODE}

##ANOTHER VARIABLE
#WSGI_WORKERS=4
#WSGI_PORT=8000
#LOCAL_PORT=8010
#WSGI_LOG_LEVEL=INFO
#HTTP_PORT=80:80
#HTTPS_PORT=443:443

version: "3"

services:
  backend:
    build: ./
    container_name: backend
    working_dir: /vpn
    ports:
      - ${LOCAL_PORT}:${WSGI_PORT}
    command:
      - ./commands/start_server_${MODE}.sh
    volumes:
      - ./src:/vpn/src
      - static_content:/vpn/src/static
      - media_content:/vpn/src/media
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  nginx:
    image: nginx:1.19
    container_name: nginx_ws
    volumes:
      - static_content:/vpn/src/static
      - media_content:/vpn/src/media
      - ./nginx:/etc/nginx/conf.d
    ports:
      - ${HTTP_PORT}
      - ${HTTPS_PORT}
    env_file:
      - .env
    depends_on:
      - backend

volumes:
  static_content: { }
  media_content: { }